apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omni-infra-provider-opennebula.fullname" . }}-config
  namespace: {{ include "omni-infra-provider-opennebula.namespace" . }}
data:
  provider-config.yaml: |
    {{- toYaml .Values.providerConfig | nindent 4 }}
