{{- if .Values.credentials.inlineAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni-infra-provider-opennebula.fullname" . }}-opennebula-auth
  namespace: {{ include "omni-infra-provider-opennebula.namespace" . }}
type: Opaque
stringData:
  credentials: {{ .Values.credentials.inlineAuth | quote }}
{{- end }}
---
{{- if .Values.omni.serviceAccount.inlineKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni-infra-provider-opennebula.fullname" . }}-omni-sa
  namespace: {{ include "omni-infra-provider-opennebula.namespace" . }}
type: Opaque
stringData:
  key: {{ .Values.omni.serviceAccount.inlineKey | quote }}
{{- end }}
