apiVersion: v1
entries:
  omni-infra-provider-opennebula:
  - apiVersion: v2
    appVersion: 0.0.0-edge.c7b0eab
    created: "2026-03-20T20:09:56.726815524Z"
    description: Omni infrastructure provider for OpenNebula
    digest: 83fabee28c489cd96ececb5fbba0f7e3dccb7446541119e387cad2c61c38e741
    home: https://github.com/SparkAIUR/omni-infra-provider-opennebula
    name: omni-infra-provider-opennebula
    sources:
    - https://github.com/SparkAIUR/omni-infra-provider-opennebula
    type: application
    urls:
    - https://sparkaiur.github.io/omni-infra-provider-opennebula/charts/omni-infra-provider-opennebula-0.0.0-edge.c7b0eab.tgz
    version: 0.0.0-edge.c7b0eab
  - apiVersion: v2
    appVersion: 0.0.0-edge.4b817e5
    created: "2026-03-20T20:09:56.726119021Z"
    description: Omni infrastructure provider for OpenNebula
    digest: 18c3069beb4a267c079225c6a191c84658c1d745511d6406d4e5fdcd09a4fb9a
    home: https://github.com/SparkAIUR/omni-infra-provider-opennebula
    name: omni-infra-provider-opennebula
    sources:
    - https://github.com/SparkAIUR/omni-infra-provider-opennebula
    type: application
    urls:
    - https://sparkaiur.github.io/omni-infra-provider-opennebula/charts/omni-infra-provider-opennebula-0.0.0-edge.4b817e5.tgz
    version: 0.0.0-edge.4b817e5
  - apiVersion: v2
    appVersion: 0.0.0-edge.205f073
    created: "2026-03-20T20:09:56.725372478Z"
    description: Omni infrastructure provider for OpenNebula
    digest: 2c61abff202d6328f02a0666190299ec1d6594755a7e9751dee18dbe58c03634
    home: https://github.com/SparkAIUR/omni-infra-provider-opennebula
    name: omni-infra-provider-opennebula
    sources:
    - https://github.com/SparkAIUR/omni-infra-provider-opennebula
    type: application
    urls:
    - https://sparkaiur.github.io/omni-infra-provider-opennebula/charts/omni-infra-provider-opennebula-0.0.0-edge.205f073.tgz
    version: 0.0.0-edge.205f073
generated: "2026-03-20T20:09:56.723526243Z"
