// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: specs/specs.proto

package specs

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MachineSpec is stored in Omni in the infra provisioner state.
type MachineSpec struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	VmId                          int32                  `protobuf:"varint,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	VmName                        string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	TemplateName                  string                 `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	TemplateId                    int32                  `protobuf:"varint,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ImageName                     string                 `protobuf:"bytes,5,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Datastore                     string                 `protobuf:"bytes,6,opt,name=datastore,proto3" json:"datastore,omitempty"`
	NetworkNames                  []string               `protobuf:"bytes,7,rep,name=network_names,json=networkNames,proto3" json:"network_names,omitempty"`
	SchematicId                   string                 `protobuf:"bytes,8,opt,name=schematic_id,json=schematicId,proto3" json:"schematic_id,omitempty"`
	TalosVersion                  string                 `protobuf:"bytes,9,opt,name=talos_version,json=talosVersion,proto3" json:"talos_version,omitempty"`
	Flavor                        string                 `protobuf:"bytes,10,opt,name=flavor,proto3" json:"flavor,omitempty"`
	Phase                         string                 `protobuf:"bytes,11,opt,name=phase,proto3" json:"phase,omitempty"`
	LastError                     string                 `protobuf:"bytes,12,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	ImageId                       int32                  `protobuf:"varint,13,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ImageSource                   string                 `protobuf:"bytes,14,opt,name=image_source,json=imageSource,proto3" json:"image_source,omitempty"`
	ImageChecksum                 string                 `protobuf:"bytes,15,opt,name=image_checksum,json=imageChecksum,proto3" json:"image_checksum,omitempty"`
	LastSuccessfulPhaseAt         string                 `protobuf:"bytes,16,opt,name=last_successful_phase_at,json=lastSuccessfulPhaseAt,proto3" json:"last_successful_phase_at,omitempty"`
	LastRetryClassification       string                 `protobuf:"bytes,17,opt,name=last_retry_classification,json=lastRetryClassification,proto3" json:"last_retry_classification,omitempty"`
	ClusterName                   string                 `protobuf:"bytes,18,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ClusterPrefix                 string                 `protobuf:"bytes,19,opt,name=cluster_prefix,json=clusterPrefix,proto3" json:"cluster_prefix,omitempty"`
	NodeRole                      string                 `protobuf:"bytes,20,opt,name=node_role,json=nodeRole,proto3" json:"node_role,omitempty"`
	SequenceNumber                int32                  `protobuf:"varint,21,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	ReservationId                 string                 `protobuf:"bytes,22,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	DatastoreId                   int32                  `protobuf:"varint,23,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id,omitempty"`
	NetworkIds                    []int32                `protobuf:"varint,24,rep,packed,name=network_ids,json=networkIds,proto3" json:"network_ids,omitempty"`
	ResolvedHypervisor            string                 `protobuf:"bytes,25,opt,name=resolved_hypervisor,json=resolvedHypervisor,proto3" json:"resolved_hypervisor,omitempty"`
	ResolvedHostId                int32                  `protobuf:"varint,26,opt,name=resolved_host_id,json=resolvedHostId,proto3" json:"resolved_host_id,omitempty"`
	ResolvedHostName              string                 `protobuf:"bytes,27,opt,name=resolved_host_name,json=resolvedHostName,proto3" json:"resolved_host_name,omitempty"`
	ResolvedClusterId             int32                  `protobuf:"varint,28,opt,name=resolved_cluster_id,json=resolvedClusterId,proto3" json:"resolved_cluster_id,omitempty"`
	ResolvedClusterName           string                 `protobuf:"bytes,29,opt,name=resolved_cluster_name,json=resolvedClusterName,proto3" json:"resolved_cluster_name,omitempty"`
	PlacementReason               string                 `protobuf:"bytes,30,opt,name=placement_reason,json=placementReason,proto3" json:"placement_reason,omitempty"`
	PlacementScoreSummary         string                 `protobuf:"bytes,31,opt,name=placement_score_summary,json=placementScoreSummary,proto3" json:"placement_score_summary,omitempty"`
	PreflightStatus               string                 `protobuf:"bytes,32,opt,name=preflight_status,json=preflightStatus,proto3" json:"preflight_status,omitempty"`
	PreflightErrors               []string               `protobuf:"bytes,33,rep,name=preflight_errors,json=preflightErrors,proto3" json:"preflight_errors,omitempty"`
	PreflightWarnings             []string               `protobuf:"bytes,34,rep,name=preflight_warnings,json=preflightWarnings,proto3" json:"preflight_warnings,omitempty"`
	ImageAction                   string                 `protobuf:"bytes,35,opt,name=image_action,json=imageAction,proto3" json:"image_action,omitempty"`
	ImageCacheHit                 bool                   `protobuf:"varint,36,opt,name=image_cache_hit,json=imageCacheHit,proto3" json:"image_cache_hit,omitempty"`
	ImageChecksumVerified         bool                   `protobuf:"varint,37,opt,name=image_checksum_verified,json=imageChecksumVerified,proto3" json:"image_checksum_verified,omitempty"`
	BootstrapProfile              string                 `protobuf:"bytes,38,opt,name=bootstrap_profile,json=bootstrapProfile,proto3" json:"bootstrap_profile,omitempty"`
	DriftStatus                   string                 `protobuf:"bytes,39,opt,name=drift_status,json=driftStatus,proto3" json:"drift_status,omitempty"`
	DriftDetails                  []string               `protobuf:"bytes,40,rep,name=drift_details,json=driftDetails,proto3" json:"drift_details,omitempty"`
	ResolvedStorageProfile        string                 `protobuf:"bytes,41,opt,name=resolved_storage_profile,json=resolvedStorageProfile,proto3" json:"resolved_storage_profile,omitempty"`
	ResolvedHostTags              []string               `protobuf:"bytes,42,rep,name=resolved_host_tags,json=resolvedHostTags,proto3" json:"resolved_host_tags,omitempty"`
	ResolvedDatastoreCapabilities []string               `protobuf:"bytes,43,rep,name=resolved_datastore_capabilities,json=resolvedDatastoreCapabilities,proto3" json:"resolved_datastore_capabilities,omitempty"`
	DiagnosticFingerprint         string                 `protobuf:"bytes,44,opt,name=diagnostic_fingerprint,json=diagnosticFingerprint,proto3" json:"diagnostic_fingerprint,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_specs_specs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{0}
}

func (x *MachineSpec) GetVmId() int32 {
	if x != nil {
		return x.VmId
	}
	return 0
}

func (x *MachineSpec) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *MachineSpec) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *MachineSpec) GetTemplateId() int32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *MachineSpec) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *MachineSpec) GetDatastore() string {
	if x != nil {
		return x.Datastore
	}
	return ""
}

func (x *MachineSpec) GetNetworkNames() []string {
	if x != nil {
		return x.NetworkNames
	}
	return nil
}

func (x *MachineSpec) GetSchematicId() string {
	if x != nil {
		return x.SchematicId
	}
	return ""
}

func (x *MachineSpec) GetTalosVersion() string {
	if x != nil {
		return x.TalosVersion
	}
	return ""
}

func (x *MachineSpec) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *MachineSpec) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *MachineSpec) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *MachineSpec) GetImageId() int32 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *MachineSpec) GetImageSource() string {
	if x != nil {
		return x.ImageSource
	}
	return ""
}

func (x *MachineSpec) GetImageChecksum() string {
	if x != nil {
		return x.ImageChecksum
	}
	return ""
}

func (x *MachineSpec) GetLastSuccessfulPhaseAt() string {
	if x != nil {
		return x.LastSuccessfulPhaseAt
	}
	return ""
}

func (x *MachineSpec) GetLastRetryClassification() string {
	if x != nil {
		return x.LastRetryClassification
	}
	return ""
}

func (x *MachineSpec) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *MachineSpec) GetClusterPrefix() string {
	if x != nil {
		return x.ClusterPrefix
	}
	return ""
}

func (x *MachineSpec) GetNodeRole() string {
	if x != nil {
		return x.NodeRole
	}
	return ""
}

func (x *MachineSpec) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MachineSpec) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *MachineSpec) GetDatastoreId() int32 {
	if x != nil {
		return x.DatastoreId
	}
	return 0
}

func (x *MachineSpec) GetNetworkIds() []int32 {
	if x != nil {
		return x.NetworkIds
	}
	return nil
}

func (x *MachineSpec) GetResolvedHypervisor() string {
	if x != nil {
		return x.ResolvedHypervisor
	}
	return ""
}

func (x *MachineSpec) GetResolvedHostId() int32 {
	if x != nil {
		return x.ResolvedHostId
	}
	return 0
}

func (x *MachineSpec) GetResolvedHostName() string {
	if x != nil {
		return x.ResolvedHostName
	}
	return ""
}

func (x *MachineSpec) GetResolvedClusterId() int32 {
	if x != nil {
		return x.ResolvedClusterId
	}
	return 0
}

func (x *MachineSpec) GetResolvedClusterName() string {
	if x != nil {
		return x.ResolvedClusterName
	}
	return ""
}

func (x *MachineSpec) GetPlacementReason() string {
	if x != nil {
		return x.PlacementReason
	}
	return ""
}

func (x *MachineSpec) GetPlacementScoreSummary() string {
	if x != nil {
		return x.PlacementScoreSummary
	}
	return ""
}

func (x *MachineSpec) GetPreflightStatus() string {
	if x != nil {
		return x.PreflightStatus
	}
	return ""
}

func (x *MachineSpec) GetPreflightErrors() []string {
	if x != nil {
		return x.PreflightErrors
	}
	return nil
}

func (x *MachineSpec) GetPreflightWarnings() []string {
	if x != nil {
		return x.PreflightWarnings
	}
	return nil
}

func (x *MachineSpec) GetImageAction() string {
	if x != nil {
		return x.ImageAction
	}
	return ""
}

func (x *MachineSpec) GetImageCacheHit() bool {
	if x != nil {
		return x.ImageCacheHit
	}
	return false
}

func (x *MachineSpec) GetImageChecksumVerified() bool {
	if x != nil {
		return x.ImageChecksumVerified
	}
	return false
}

func (x *MachineSpec) GetBootstrapProfile() string {
	if x != nil {
		return x.BootstrapProfile
	}
	return ""
}

func (x *MachineSpec) GetDriftStatus() string {
	if x != nil {
		return x.DriftStatus
	}
	return ""
}

func (x *MachineSpec) GetDriftDetails() []string {
	if x != nil {
		return x.DriftDetails
	}
	return nil
}

func (x *MachineSpec) GetResolvedStorageProfile() string {
	if x != nil {
		return x.ResolvedStorageProfile
	}
	return ""
}

func (x *MachineSpec) GetResolvedHostTags() []string {
	if x != nil {
		return x.ResolvedHostTags
	}
	return nil
}

func (x *MachineSpec) GetResolvedDatastoreCapabilities() []string {
	if x != nil {
		return x.ResolvedDatastoreCapabilities
	}
	return nil
}

func (x *MachineSpec) GetDiagnosticFingerprint() string {
	if x != nil {
		return x.DiagnosticFingerprint
	}
	return ""
}

// NameReservationSpec stores cluster-role sequence allocations for deterministic VM naming.
type NameReservationSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClusterName      string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ClusterPrefix    string                 `protobuf:"bytes,2,opt,name=cluster_prefix,json=clusterPrefix,proto3" json:"cluster_prefix,omitempty"`
	Role             string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Ordinal          int32                  `protobuf:"varint,4,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	VmName           string                 `protobuf:"bytes,5,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	MachineRequestId string                 `protobuf:"bytes,6,opt,name=machine_request_id,json=machineRequestId,proto3" json:"machine_request_id,omitempty"`
	MachineUuid      string                 `protobuf:"bytes,7,opt,name=machine_uuid,json=machineUuid,proto3" json:"machine_uuid,omitempty"`
	StateResourceId  string                 `protobuf:"bytes,8,opt,name=state_resource_id,json=stateResourceId,proto3" json:"state_resource_id,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NameReservationSpec) Reset() {
	*x = NameReservationSpec{}
	mi := &file_specs_specs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameReservationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameReservationSpec) ProtoMessage() {}

func (x *NameReservationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameReservationSpec.ProtoReflect.Descriptor instead.
func (*NameReservationSpec) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{1}
}

func (x *NameReservationSpec) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *NameReservationSpec) GetClusterPrefix() string {
	if x != nil {
		return x.ClusterPrefix
	}
	return ""
}

func (x *NameReservationSpec) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NameReservationSpec) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *NameReservationSpec) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *NameReservationSpec) GetMachineRequestId() string {
	if x != nil {
		return x.MachineRequestId
	}
	return ""
}

func (x *NameReservationSpec) GetMachineUuid() string {
	if x != nil {
		return x.MachineUuid
	}
	return ""
}

func (x *NameReservationSpec) GetStateResourceId() string {
	if x != nil {
		return x.StateResourceId
	}
	return ""
}

func (x *NameReservationSpec) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_specs_specs_proto protoreflect.FileDescriptor

const file_specs_specs_proto_rawDesc = "" +
	"\n" +
	"\x11specs/specs.proto\x12\x0fopennebulaspecs\"\x81\x0e\n" +
	"\vMachineSpec\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\x05R\x04vmId\x12\x17\n" +
	"\avm_name\x18\x02 \x01(\tR\x06vmName\x12#\n" +
	"\rtemplate_name\x18\x03 \x01(\tR\ftemplateName\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\x05R\n" +
	"templateId\x12\x1d\n" +
	"\n" +
	"image_name\x18\x05 \x01(\tR\timageName\x12\x1c\n" +
	"\tdatastore\x18\x06 \x01(\tR\tdatastore\x12#\n" +
	"\rnetwork_names\x18\a \x03(\tR\fnetworkNames\x12!\n" +
	"\fschematic_id\x18\b \x01(\tR\vschematicId\x12#\n" +
	"\rtalos_version\x18\t \x01(\tR\ftalosVersion\x12\x16\n" +
	"\x06flavor\x18\n" +
	" \x01(\tR\x06flavor\x12\x14\n" +
	"\x05phase\x18\v \x01(\tR\x05phase\x12\x1d\n" +
	"\n" +
	"last_error\x18\f \x01(\tR\tlastError\x12\x19\n" +
	"\bimage_id\x18\r \x01(\x05R\aimageId\x12!\n" +
	"\fimage_source\x18\x0e \x01(\tR\vimageSource\x12%\n" +
	"\x0eimage_checksum\x18\x0f \x01(\tR\rimageChecksum\x127\n" +
	"\x18last_successful_phase_at\x18\x10 \x01(\tR\x15lastSuccessfulPhaseAt\x12:\n" +
	"\x19last_retry_classification\x18\x11 \x01(\tR\x17lastRetryClassification\x12!\n" +
	"\fcluster_name\x18\x12 \x01(\tR\vclusterName\x12%\n" +
	"\x0ecluster_prefix\x18\x13 \x01(\tR\rclusterPrefix\x12\x1b\n" +
	"\tnode_role\x18\x14 \x01(\tR\bnodeRole\x12'\n" +
	"\x0fsequence_number\x18\x15 \x01(\x05R\x0esequenceNumber\x12%\n" +
	"\x0ereservation_id\x18\x16 \x01(\tR\rreservationId\x12!\n" +
	"\fdatastore_id\x18\x17 \x01(\x05R\vdatastoreId\x12\x1f\n" +
	"\vnetwork_ids\x18\x18 \x03(\x05R\n" +
	"networkIds\x12/\n" +
	"\x13resolved_hypervisor\x18\x19 \x01(\tR\x12resolvedHypervisor\x12(\n" +
	"\x10resolved_host_id\x18\x1a \x01(\x05R\x0eresolvedHostId\x12,\n" +
	"\x12resolved_host_name\x18\x1b \x01(\tR\x10resolvedHostName\x12.\n" +
	"\x13resolved_cluster_id\x18\x1c \x01(\x05R\x11resolvedClusterId\x122\n" +
	"\x15resolved_cluster_name\x18\x1d \x01(\tR\x13resolvedClusterName\x12)\n" +
	"\x10placement_reason\x18\x1e \x01(\tR\x0fplacementReason\x126\n" +
	"\x17placement_score_summary\x18\x1f \x01(\tR\x15placementScoreSummary\x12)\n" +
	"\x10preflight_status\x18  \x01(\tR\x0fpreflightStatus\x12)\n" +
	"\x10preflight_errors\x18! \x03(\tR\x0fpreflightErrors\x12-\n" +
	"\x12preflight_warnings\x18\" \x03(\tR\x11preflightWarnings\x12!\n" +
	"\fimage_action\x18# \x01(\tR\vimageAction\x12&\n" +
	"\x0fimage_cache_hit\x18$ \x01(\bR\rimageCacheHit\x126\n" +
	"\x17image_checksum_verified\x18% \x01(\bR\x15imageChecksumVerified\x12+\n" +
	"\x11bootstrap_profile\x18& \x01(\tR\x10bootstrapProfile\x12!\n" +
	"\fdrift_status\x18' \x01(\tR\vdriftStatus\x12#\n" +
	"\rdrift_details\x18( \x03(\tR\fdriftDetails\x128\n" +
	"\x18resolved_storage_profile\x18) \x01(\tR\x16resolvedStorageProfile\x12,\n" +
	"\x12resolved_host_tags\x18* \x03(\tR\x10resolvedHostTags\x12F\n" +
	"\x1fresolved_datastore_capabilities\x18+ \x03(\tR\x1dresolvedDatastoreCapabilities\x125\n" +
	"\x16diagnostic_fingerprint\x18, \x01(\tR\x15diagnosticFingerprint\"\xc2\x02\n" +
	"\x13NameReservationSpec\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12%\n" +
	"\x0ecluster_prefix\x18\x02 \x01(\tR\rclusterPrefix\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\aordinal\x18\x04 \x01(\x05R\aordinal\x12\x17\n" +
	"\avm_name\x18\x05 \x01(\tR\x06vmName\x12,\n" +
	"\x12machine_request_id\x18\x06 \x01(\tR\x10machineRequestId\x12!\n" +
	"\fmachine_uuid\x18\a \x01(\tR\vmachineUuid\x12*\n" +
	"\x11state_resource_id\x18\b \x01(\tR\x0fstateResourceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAtB?Z=github.com/SparkAIUR/omni-infra-provider-opennebula/api/specsb\x06proto3"

var (
	file_specs_specs_proto_rawDescOnce sync.Once
	file_specs_specs_proto_rawDescData []byte
)

func file_specs_specs_proto_rawDescGZIP() []byte {
	file_specs_specs_proto_rawDescOnce.Do(func() {
		file_specs_specs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_specs_specs_proto_rawDesc), len(file_specs_specs_proto_rawDesc)))
	})
	return file_specs_specs_proto_rawDescData
}

var file_specs_specs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_specs_specs_proto_goTypes = []any{
	(*MachineSpec)(nil),         // 0: opennebulaspecs.MachineSpec
	(*NameReservationSpec)(nil), // 1: opennebulaspecs.NameReservationSpec
}
var file_specs_specs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_specs_specs_proto_init() }
func file_specs_specs_proto_init() {
	if File_specs_specs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_specs_specs_proto_rawDesc), len(file_specs_specs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_specs_specs_proto_goTypes,
		DependencyIndexes: file_specs_specs_proto_depIdxs,
		MessageInfos:      file_specs_specs_proto_msgTypes,
	}.Build()
	File_specs_specs_proto = out.File
	file_specs_specs_proto_goTypes = nil
	file_specs_specs_proto_depIdxs = nil
}
