// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: specs/specs.proto

package specs

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MachineSpec is stored in Omni in the infra provisioner state.
type MachineSpec struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	VmId                    int32                  `protobuf:"varint,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	VmName                  string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	TemplateName            string                 `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	TemplateId              int32                  `protobuf:"varint,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ImageName               string                 `protobuf:"bytes,5,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Datastore               string                 `protobuf:"bytes,6,opt,name=datastore,proto3" json:"datastore,omitempty"`
	NetworkNames            []string               `protobuf:"bytes,7,rep,name=network_names,json=networkNames,proto3" json:"network_names,omitempty"`
	SchematicId             string                 `protobuf:"bytes,8,opt,name=schematic_id,json=schematicId,proto3" json:"schematic_id,omitempty"`
	TalosVersion            string                 `protobuf:"bytes,9,opt,name=talos_version,json=talosVersion,proto3" json:"talos_version,omitempty"`
	Flavor                  string                 `protobuf:"bytes,10,opt,name=flavor,proto3" json:"flavor,omitempty"`
	Phase                   string                 `protobuf:"bytes,11,opt,name=phase,proto3" json:"phase,omitempty"`
	LastError               string                 `protobuf:"bytes,12,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	ImageId                 int32                  `protobuf:"varint,13,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ImageSource             string                 `protobuf:"bytes,14,opt,name=image_source,json=imageSource,proto3" json:"image_source,omitempty"`
	ImageChecksum           string                 `protobuf:"bytes,15,opt,name=image_checksum,json=imageChecksum,proto3" json:"image_checksum,omitempty"`
	LastSuccessfulPhaseAt   string                 `protobuf:"bytes,16,opt,name=last_successful_phase_at,json=lastSuccessfulPhaseAt,proto3" json:"last_successful_phase_at,omitempty"`
	LastRetryClassification string                 `protobuf:"bytes,17,opt,name=last_retry_classification,json=lastRetryClassification,proto3" json:"last_retry_classification,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_specs_specs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{0}
}

func (x *MachineSpec) GetVmId() int32 {
	if x != nil {
		return x.VmId
	}
	return 0
}

func (x *MachineSpec) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *MachineSpec) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *MachineSpec) GetTemplateId() int32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *MachineSpec) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *MachineSpec) GetDatastore() string {
	if x != nil {
		return x.Datastore
	}
	return ""
}

func (x *MachineSpec) GetNetworkNames() []string {
	if x != nil {
		return x.NetworkNames
	}
	return nil
}

func (x *MachineSpec) GetSchematicId() string {
	if x != nil {
		return x.SchematicId
	}
	return ""
}

func (x *MachineSpec) GetTalosVersion() string {
	if x != nil {
		return x.TalosVersion
	}
	return ""
}

func (x *MachineSpec) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *MachineSpec) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *MachineSpec) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *MachineSpec) GetImageId() int32 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *MachineSpec) GetImageSource() string {
	if x != nil {
		return x.ImageSource
	}
	return ""
}

func (x *MachineSpec) GetImageChecksum() string {
	if x != nil {
		return x.ImageChecksum
	}
	return ""
}

func (x *MachineSpec) GetLastSuccessfulPhaseAt() string {
	if x != nil {
		return x.LastSuccessfulPhaseAt
	}
	return ""
}

func (x *MachineSpec) GetLastRetryClassification() string {
	if x != nil {
		return x.LastRetryClassification
	}
	return ""
}

var File_specs_specs_proto protoreflect.FileDescriptor

const file_specs_specs_proto_rawDesc = "" +
	"\n" +
	"\x11specs/specs.proto\x12\x0fopennebulaspecs\"\xd2\x04\n" +
	"\vMachineSpec\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\x05R\x04vmId\x12\x17\n" +
	"\avm_name\x18\x02 \x01(\tR\x06vmName\x12#\n" +
	"\rtemplate_name\x18\x03 \x01(\tR\ftemplateName\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\x05R\n" +
	"templateId\x12\x1d\n" +
	"\n" +
	"image_name\x18\x05 \x01(\tR\timageName\x12\x1c\n" +
	"\tdatastore\x18\x06 \x01(\tR\tdatastore\x12#\n" +
	"\rnetwork_names\x18\a \x03(\tR\fnetworkNames\x12!\n" +
	"\fschematic_id\x18\b \x01(\tR\vschematicId\x12#\n" +
	"\rtalos_version\x18\t \x01(\tR\ftalosVersion\x12\x16\n" +
	"\x06flavor\x18\n" +
	" \x01(\tR\x06flavor\x12\x14\n" +
	"\x05phase\x18\v \x01(\tR\x05phase\x12\x1d\n" +
	"\n" +
	"last_error\x18\f \x01(\tR\tlastError\x12\x19\n" +
	"\bimage_id\x18\r \x01(\x05R\aimageId\x12!\n" +
	"\fimage_source\x18\x0e \x01(\tR\vimageSource\x12%\n" +
	"\x0eimage_checksum\x18\x0f \x01(\tR\rimageChecksum\x127\n" +
	"\x18last_successful_phase_at\x18\x10 \x01(\tR\x15lastSuccessfulPhaseAt\x12:\n" +
	"\x19last_retry_classification\x18\x11 \x01(\tR\x17lastRetryClassificationB?Z=github.com/SparkAIUR/omni-infra-provider-opennebula/api/specsb\x06proto3"

var (
	file_specs_specs_proto_rawDescOnce sync.Once
	file_specs_specs_proto_rawDescData []byte
)

func file_specs_specs_proto_rawDescGZIP() []byte {
	file_specs_specs_proto_rawDescOnce.Do(func() {
		file_specs_specs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_specs_specs_proto_rawDesc), len(file_specs_specs_proto_rawDesc)))
	})
	return file_specs_specs_proto_rawDescData
}

var file_specs_specs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_specs_specs_proto_goTypes = []any{
	(*MachineSpec)(nil), // 0: opennebulaspecs.MachineSpec
}
var file_specs_specs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_specs_specs_proto_init() }
func file_specs_specs_proto_init() {
	if File_specs_specs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_specs_specs_proto_rawDesc), len(file_specs_specs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_specs_specs_proto_goTypes,
		DependencyIndexes: file_specs_specs_proto_depIdxs,
		MessageInfos:      file_specs_specs_proto_msgTypes,
	}.Build()
	File_specs_specs_proto = out.File
	file_specs_specs_proto_goTypes = nil
	file_specs_specs_proto_depIdxs = nil
}
