syntax = "proto3";
package opennebulaspecs;

option go_package = "github.com/SparkAIUR/omni-infra-provider-opennebula/api/specs";

// MachineSpec is stored in Omni in the infra provisioner state.
message MachineSpec {
  int32 vm_id = 1;
  string vm_name = 2;
  string template_name = 3;
  int32 template_id = 4;
  string image_name = 5;
  string datastore = 6;
  repeated string network_names = 7;
  string schematic_id = 8;
  string talos_version = 9;
  string flavor = 10;
  string phase = 11;
  string last_error = 12;
}
